import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '@/components/Home/Hero'
import { useEffect } from 'react'
import { loadPosts } from '@/lib/load-posts'
import FeaturedPost from '@/components/Posts/Post/FeaturedPost'
import PostsGrid from '@/components/Posts/PostsGrid'

export default function Home({posts}) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-screen-lg mx-auto'>
        <Hero />
        <FeaturedPost post={posts.posts[0]} />
        <PostsGrid posts={posts} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  // we dont have to fetch our api but instead call the same
  const posts = await loadPosts()

  return { props: { posts }}
}

